### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by momadacoding** [alexbowe/smoothbrain#45]
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-05 15:10:28
相关插件：⁨smoothbrain⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.operations", line 250, in wrapped_done
  File "C:\Users\haolly\AppData\Roaming\Anki2\addons21\smoothbrain\__init__.py", line 117, in update_card
    note = mw.col.new_note(model)
  File "anki.collection", line 567, in new_note
  File "anki.notes", line 52, in __init__
  File "anki._backend_generated", line 1030, in new_note
  File "anki._backend", line 151, in _run_command
anki.errors.NotFoundError: 数据库存在不一致问题。请使用「检查数据库」操作。

**Comment by momadacoding** [comment]
nodetype needs to be "Basic"
